todo_app/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.app, name='app'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('register/', views.register, name='register'),
    path('login/', views.user_log_in, name='login'),
    path('logout/', views.user_log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('<int:todo_id>/delete_todo/', views.delete_todo, name='delete_todo'),
]

todo_app/todo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('app.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

todo_app/app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.CharField(max_length=80)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.item

todo_app/app/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]

todo_app/app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Todo
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login')
def app(request):
    context = {}
    all_todo = Todo.objects.filter(user=request.user).order_by('-timestamp')
    if all_todo:
        context = {
            'all_todo': all_todo,
        }
    return render(request, 'app.html', context)


@login_required(login_url='/login')
def add_todo(request):
    user = request.user
    item = request.POST.get('item')
    if item is not None and item is not '':
        Todo.objects.create(user=user, item=item)
    return redirect('app:app')


@login_required(login_url='/login')
def delete_todo(request, todo_id):
    Todo.objects.get(user=request.user, id=todo_id).delete()
    return redirect('app:app')


def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('app:login')
    return render(request, 'register.html')


@login_required(login_url='/login')
def profile(request):
    return render(request, 'profile.html')


def user_log_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('app:app')
        else:
            context = {
                'message': "Didn't match with any user we have",
            }
            return render(request, 'login.html', context)
    context = {}

    return render(request, 'login.html', context)


def user_log_out(request):
    logout(request)
    return redirect('app:app')

todo_app/templates/app.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home | Todo</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="container row">
    <div class="row">
        <form action="{% url 'app:add_todo' %}" method="post">
            <div class="row">
                <form class="col s12" method="post" action="{% url 'app:add_todo' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            <input id="item" type="text" class="validate" name="item" style="font-family: fira code">
                            <label for="item">Add Item..</label>
                        </div>
                        <button class="btn waves-effect waves-light" type="submit" name="action">Add Item
                            <i class="material-icons right">add</i>
                        </button>
                    </div>
                </form>
            </div>
        </form>
    </div>
</div>
{% if all_todo %}
<div class="container">
    <ul class="collection with-header">
        <li class="collection-header"><h5>Todo List</h5></li>
        {% for todo in all_todo %}
        <li class="collection-item">
            <div>
                {{ todo.item }}
                <form action="{% url 'app:delete_todo' todo.id %}" class="secondary-content" method="post">
                    {% csrf_token %}
                    <button type="submit"
                            style="border: none; background-color: none; outline: none; border-radius: 5px;"><a href=""
                                                                                                                class="waves-effect waves-light modal-trigger"><i
                            class="material-icons">delete</i></a></button>
                </form>
            </div>
        </li>
        {% endfor %}
    </ul>
    <!-- Modal Structure -->
</div>

{% else %}
<div class="container">
    <h5>No todo are available</h5>
</div>

{% endif %}

{% endblock content %}
</body>
</html>

todo_app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<nav>
    <div class="container nav-wrapper">
        <a href="/" class="brand-logo">Todo App</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'app:register' %}">Register</a></li>
            <li><a href="{% url 'app:login' %}">Login</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'app:logout' %}">Logout</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li><a href="{% url 'app:profile' %}">Profile</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

todo_app/templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'app:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" id="username" placeholder="username">
        <input type="password" name="password" id="password" placeholder="Confirm Password">
        {% if message %}
            <p><strong>{{ message }}</strong></p>
        {% endif %}
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>
    <p>Don't have an account? <a href="{% url 'app:register' %}">Sign Up</a></p>
</div>
{% endblock content %}
</body>
</html>

todo_app/templates/profile.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Profile</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h4>Hello, {{ user.username }}</h4>
    </div>
{% endblock content %}
</body>
</html>

todo_app/templates/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'app:register' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" id="username" placeholder="username">
        <input type="email" name="email" id="email" placeholder="Email">
        <input type="password" name="password1" id="password1" placeholder="Password">
        <input type="password" name="password2" id="password2" placeholder="Confirm Password">
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>
    <p>Already have an account? <a href="{% url 'app:login' %}">Login</a></p>
</div>
{% endblock content %}
</body>
</html>